name: CI
on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build app
        run: ./gradlew spotlessCheck assembleDevDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Yomiko-${{ github.sha }}.apk
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
